# Form implementation generated from reading ui file 'VentanaDeErrores.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(332, 153)
        self.lbl_error = QtWidgets.QLabel(Form)
        self.lbl_error.setGeometry(QtCore.QRect(30, 40, 271, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_error.setFont(font)
        self.lbl_error.setObjectName("lbl_error")
        self.btn_aceptar = QtWidgets.QPushButton(Form)
        self.btn_aceptar.setGeometry(QtCore.QRect(130, 90, 75, 23))
        self.btn_aceptar.setObjectName("btn_aceptar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lbl_error.setText(_translate("Form", "Error: "))
        self.btn_aceptar.setText(_translate("Form", "Aceptar"))
