# Form implementation generated from reading ui file 'VentanaBuscarEntidad.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_form_buscar_entidad(object):
    def setupUi(self, form_buscar_entidad):
        form_buscar_entidad.setObjectName("form_buscar_entidad")
        form_buscar_entidad.resize(475, 400)
        self.btn_buscar = QtWidgets.QPushButton(form_buscar_entidad)
        self.btn_buscar.setGeometry(QtCore.QRect(70, 310, 75, 23))
        self.btn_buscar.setObjectName("btn_buscar")
        self.lbl_nombre = QtWidgets.QLabel(form_buscar_entidad)
        self.lbl_nombre.setGeometry(QtCore.QRect(50, 50, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_nombre.setFont(font)
        self.lbl_nombre.setObjectName("lbl_nombre")
        self.txt_nombre = QtWidgets.QLineEdit(form_buscar_entidad)
        self.txt_nombre.setEnabled(False)
        self.txt_nombre.setGeometry(QtCore.QRect(210, 50, 180, 20))
        self.txt_nombre.setAutoFillBackground(True)
        self.txt_nombre.setObjectName("txt_nombre")
        self.txt_CI_RUC = QtWidgets.QLineEdit(form_buscar_entidad)
        self.txt_CI_RUC.setGeometry(QtCore.QRect(210, 10, 180, 20))
        self.txt_CI_RUC.setObjectName("txt_CI_RUC")
        self.btn_cancelar = QtWidgets.QPushButton(form_buscar_entidad)
        self.btn_cancelar.setGeometry(QtCore.QRect(340, 310, 75, 23))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.btn_aceptar = QtWidgets.QPushButton(form_buscar_entidad)
        self.btn_aceptar.setGeometry(QtCore.QRect(200, 310, 75, 23))
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.lbl_CI_RUC = QtWidgets.QLabel(form_buscar_entidad)
        self.lbl_CI_RUC.setGeometry(QtCore.QRect(50, 10, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_CI_RUC.setFont(font)
        self.lbl_CI_RUC.setObjectName("lbl_CI_RUC")

        self.retranslateUi(form_buscar_entidad)
        QtCore.QMetaObject.connectSlotsByName(form_buscar_entidad)

    def retranslateUi(self, form_buscar_entidad):
        _translate = QtCore.QCoreApplication.translate
        form_buscar_entidad.setWindowTitle(_translate("form_buscar_entidad", "Form"))
        self.btn_buscar.setText(_translate("form_buscar_entidad", "Buscar"))
        self.lbl_nombre.setText(_translate("form_buscar_entidad", "Nombre:"))
        self.btn_cancelar.setText(_translate("form_buscar_entidad", "Cancelar"))
        self.btn_aceptar.setText(_translate("form_buscar_entidad", "Aceptar"))
        self.lbl_CI_RUC.setText(_translate("form_buscar_entidad", "CI/RUC:"))
