# Form implementation generated from reading ui file 'VentanaMostrarEntidades.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(718, 412)
        self.jgd_tabla_entidades = QtWidgets.QTableWidget(Form)
        self.jgd_tabla_entidades.setEnabled(True)
        self.jgd_tabla_entidades.setGeometry(QtCore.QRect(20, 20, 531, 361))
        self.jgd_tabla_entidades.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.jgd_tabla_entidades.setObjectName("jgd_tabla_entidades")
        self.jgd_tabla_entidades.setColumnCount(5)
        self.jgd_tabla_entidades.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.jgd_tabla_entidades.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.jgd_tabla_entidades.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.jgd_tabla_entidades.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.jgd_tabla_entidades.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.jgd_tabla_entidades.setHorizontalHeaderItem(4, item)
        self.jgd_tabla_entidades.horizontalHeader().setCascadingSectionResizes(False)
        self.jgd_tabla_entidades.verticalHeader().setCascadingSectionResizes(False)
        self.btn_editar = QtWidgets.QPushButton(Form)
        self.btn_editar.setGeometry(QtCore.QRect(600, 140, 75, 23))
        self.btn_editar.setObjectName("btn_editar")
        self.btn_eliminar = QtWidgets.QPushButton(Form)
        self.btn_eliminar.setGeometry(QtCore.QRect(600, 230, 75, 23))
        self.btn_eliminar.setObjectName("btn_eliminar")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.jgd_tabla_entidades.horizontalHeaderItem(0)
        item.setText(_translate("Form", "CI/RUC"))
        item = self.jgd_tabla_entidades.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nombre"))
        item = self.jgd_tabla_entidades.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Teléfono"))
        item = self.jgd_tabla_entidades.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Correo electrónico"))
        item = self.jgd_tabla_entidades.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Dirección"))
        self.btn_editar.setText(_translate("Form", "Editar"))
        self.btn_eliminar.setText(_translate("Form", "Eliminar"))
